In [4]:
# Numerical arrays.
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [5]:
# Numerical arrays.
import numpy as np

# A 2D array of integers.
X = np.array([[1, 2, 3], [4, 5, 6]])

# Show.
print(X)


[[1 2 3]
 [4 5 6]]


In [9]:
import numpy as np

[
    ["a", "b"],
    ["c", "d"]
]

[['a', 'b'], ['c', 'd']]

In [10]:
# Num of dimensions
print(X.ndim)

2


In [11]:
# Shape of the array
print(X.shape)

(2, 3)


In [ ]:
# type of the elements.
print(X.dtype)

# int 64 means = python will let us have any amount of bits. 
# The numpy restricts us to 64 bits. 
# For numpy to be efficient it needs to have the same amount of bits.
# 64 bits is the highest amount in a CPU currently. 

int64


In [7]:
import numpy as np

# two arrays.
A = np.array([[1, 2]
              3, 4])
B = np.array([[5, 6]
              7, 8])

print(A)
print(B)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (178246496.py, line 4)

In [ ]:
A + 5

array([[6, 7]])

In [ ]:
A + B

array([[4, 6]])